Estate_Hub/Models/CalenderHelpers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proptiwise.Models
{
    public static class CalendarHelpers
    {
        //Google Calender

        public static string GoogleCalendar(this HtmlHelper helper, string linkText, string what, DateTime start, DateTime? end, string description, string location, string websiteName, string websiteAddress, string attributes)
        {
            //parse dates
            var dates = start.ToString("yyyyMMddTHHmmssZ");
            if (end.HasValue && end > start)
            {
                dates += "/" + end.Value.ToString("yyyyMMddTHHmmssZ");
            }
            else
            {
                dates += "/" + start.ToString("yyyyMMddTHHmmssZ");
            }

            var path = string.Format("http://www.google.com/calendar/event?action=TEMPLATE&text={0}&dates={1}&details={2}&location={3}&trp=false&sprop={4}&sprop=name:{5}",
                                            what,
                                            dates,
                                            description,
                                            location,
                                            websiteName,
                                            websiteAddress);

            var calendar = string.Format("<a href='{0}' target='_blank' {1}>{2}</a>",
                                            HttpUtility.UrlPathEncode(path),
                                            helper.AttributeEncode(attributes),
                                            linkText);

            return calendar;
        }

        public static string GoogleCalendar(this HtmlHelper helper, string linkText, string what, DateTime start, DateTime? end, string description, string location, string websiteName, string websiteAddress)
        {
            return GoogleCalendar(helper, linkText, what, start, end, description, location, websiteName, websiteAddress, "");
        }

        public static string GoogleCalendar(this HtmlHelper helper, string linkText, string what, DateTime start, string description)
        {
            return GoogleCalendar(helper, linkText, what, start, null, description, "", "", "", "");
        }
    }
}

Estate_Hub/Models/Plan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int PlanID { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> MaxZipCodes { get; set; }
        public Nullable<int> MaxCities { get; set; }
        public Nullable<int> MaxStates { get; set; }
        public Nullable<decimal> PriceMonthly { get; set; }
        public Nullable<decimal> PriceYearly { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}

Estate_Hub/Models/TenancyAgreement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenancyAgreement
    {
        public TenancyAgreement()
        {
            this.damage_intventory = new HashSet<damage_intventory>();
            this.tbl_invoice = new HashSet<tbl_invoice>();
            this.TenancyDetails = new HashSet<TenancyDetail>();
        }
    
        public int TenancyAgreementId { get; set; }
        public Nullable<System.DateTime> FromAgreementDate { get; set; }
        public Nullable<System.DateTime> ToAgreementDate { get; set; }
        public string Duration { get; set; }
        public string TenancyAgreementData { get; set; }
        public string Signatures { get; set; }
        public string SignatureTenant { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> lastmonthdate { get; set; }
        public Nullable<int> RenewStatus { get; set; }
        public Nullable<System.DateTime> Checkoutdate { get; set; }
        public Nullable<int> Paymentstatus { get; set; }
        public Nullable<int> Sendstatus { get; set; }
        public string Cancelcomment { get; set; }
    
        public virtual ICollection<damage_intventory> damage_intventory { get; set; }
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}

Estate_Hub/Controllers/FrontController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proptiwise.Models;
using Proptiwise.ViewModels;
using System.Net.Mail;
using System.Data;
using PagedList;
using System.Net;
using System.IO;
using System.Text;
using System.Web.UI;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Reflection;
using iTextSharp.text.html.simpleparser;
using Microsoft.Reporting.WebForms;
using System.Data.Entity.Core.Objects;
using System.Diagnostics;
using Newtonsoft.Json;
using System.Web.Script.Serialization;


namespace Proptiwise.Controllers
{
    public class FrontController : Controller
    {



        dbrealestateEntities db = new dbrealestateEntities();
        public static int pagesize1, i = 0;
        public static bool ifprpdetail = false;
        static int? page1;
        static int cmd = 0;

        public static string regSmtpUserName
        {
            get
            {
                return ConfigurationManager.AppSettings["regSMTPUsername"];
            }
        }

        public static string regSmtpPassword
        {
            get
            {
                return ConfigurationManager.AppSettings["regSMTPPassword"];
            }
        }

        public static string regSenderEmail
        {
            get
            {
                return ConfigurationManager.AppSettings["regSenderEmail"];
            }
        }

        public static string SmtpUserName
        {
            get
            {
                return ConfigurationManager.AppSettings["SMTPUsername"];
            }
        }

        public static string SmtpPassword
        {
            get
            {
                return ConfigurationManager.AppSettings["SMTPPassword"];
            }
        }

        public static string SmtpPort
        {
            get
            {
                return ConfigurationManager.AppSettings["SMTPServerPort"];
            }
        }

        public static string SenderEmail
        {
            get
            {
                return ConfigurationManager.AppSettings["SenderEmail"];
            }
        }

        public static string SmtpHost
        {
            get
            {
                return ConfigurationManager.AppSettings["SmtpHost"];
            }
        }
        private void SendPDFEmail(DataTable dt, string to, string cc, string bcc, string subject, string body, string heading, string filename)
        {

            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter hw = new HtmlTextWriter(sw))
                {
                    // string companyName = "ASPSnippets";
                    // int orderNo = 2303;
                    StringBuilder sb = new StringBuilder();
                    sb.Append(heading);
                    sb.Append("<br>");
                    sb.Append("<br>");
                    sb.Append("<br>");
                    sb.Append("<table border = '1'>");
                    sb.Append("<tr>");

                    for (int k = 0; k < dt.Columns.Count; k++)
                    {
                        // sb.Append("<th style = 'background-color: #D20B0C;color:#ffffff'>");
                        sb.Append("<th>");
                        sb.Append(dt.Columns[k].ToString());
                        sb.Append("</th>");
                    }
                    sb.Append("</tr>");
                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        sb.Append("<tr>");
                        for (int j = 0; j < dt.Columns.Count; j++)
                        {
                            sb.Append("<td>");
                            sb.Append(dt.Rows[i][j].ToString());
                            sb.Append("</td>");
                        }
                        sb.Append("</tr>");
                    }
                    sb.Append("</table>");
                    StringReader sr = new StringReader(sb.ToString());
                    Document pdfDoc = new Document();
                    pdfDoc.SetPageSize(iTextSharp.text.PageSize.A4.Rotate());
                    HTMLWorker htmlparser = new HTMLWorker(pdfDoc);
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        PdfWriter writer = PdfWriter.GetInstance(pdfDoc, memoryStream);
                        pdfDoc.Open();
                        htmlparser.Parse(sr);
                        pdfDoc.Close();
                        byte[] bytes = memoryStream.ToArray();
                        memoryStream.Close();
                        MailMessage mm = new MailMessage();
                        mm.From = new MailAddress(SenderEmail);
                        if (to != null && to != "")
                        {
                            string[] multito = to.Split(',');
                            foreach (string idto in multito)
                                mm.To.Add(idto);
                        }
                        if (cc != null && cc != "")
                        {
                            string[] multicc = cc.Split(',');
                            foreach (string idcc in multicc)
                                mm.CC.Add(idcc);
                        }
                        if (bcc != null && bcc != "")
                        {
                            string[] multibcc = bcc.Split(',');
                            foreach (string idbcc in multibcc)
                                mm.Bcc.Add(idbcc);
                        }
                        mm.Subject = subject;
                        mm.Body = body;
                        mm.Attachments.Add(new Attachment(new MemoryStream(bytes), filename + ".pdf"));
                        mm.IsBodyHtml = true;
                        SmtpClient smtp = new SmtpClient();
                        smtp.Host = SmtpHost;
                        smtp.EnableSsl = false;
                        NetworkCredential NetworkCred = new NetworkCredential();
                        NetworkCred.UserName = SmtpUserName;
                        NetworkCred.Password = SmtpPassword;
                        smtp.UseDefaultCredentials = true;
                        smtp.Credentials = NetworkCred;
                        smtp.Port = Convert.ToInt32(SmtpPort);
                        smtp.Send(mm);
                    }
                }
            }
        }

        public static DataTable ToDataTable<T>(List<T> items)
        {
            DataTable dataTable = new DataTable(typeof(T).Name);

            //Get all the properties
            PropertyInfo[] Props = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);
            foreach (PropertyInfo prop in Props)
            {
                //Setting column names as Property names
                dataTable.Columns.Add(prop.Name);
            }
            foreach (T item in items)
            {
                var values = new object[Props.Length];
                for (int i = 0; i < Props.Length; i++)
                {
                    //inserting property values to datatable rows
                    values[i] = Props[i].GetValue(item, null);
                }
                dataTable.Rows.Add(values);
            }
            //put a breakpoint here and check datatable
            return dataTable;
        }

        public void ExportToPdf(DataTable myDataTable, string heading)
        {
            //Document pdfDoc = new Document(PageSize.A4, 10, 10, 10, 10);
            Document pdfDoc = new Document();
            pdfDoc.SetPageSize(iTextSharp.text.PageSize.A4.Rotate());
            try
            {
                PdfWriter.GetInstance(pdfDoc, System.Web.HttpContext.Current.Response.OutputStream);

                pdfDoc.Open();
                Chunk c = new Chunk(heading, FontFactory.GetFont("Verdana", 10));
                Paragraph p = new Paragraph();
                p.Alignment = Element.ALIGN_CENTER;
                p.Add(c);
                pdfDoc.Add(p);
                Phrase phrase1 = new Phrase(Environment.NewLine);
                pdfDoc.Add(phrase1);
                Font font8 = FontFactory.GetFont("ARIAL", 7);
                DataTable dt = myDataTable;
                if (dt != null)
                {
                    //Craete instance of the pdf table and set the number of column in that table  
                    PdfPTable PdfTable = new PdfPTable(dt.Columns.Count - 3);

                    PdfPCell PdfPCell = null;
                    for (int column = 0; column < dt.Columns.Count - 3; column++)
                    {
                        PdfPCell = new PdfPCell(new Phrase(new Chunk(dt.Columns[column].ToString(), font8)));
                        PdfPCell.Padding = 3;
                        PdfTable.AddCell(PdfPCell);
                    }
                    for (int rows = 0; rows < dt.Rows.Count; rows++)
                    {
                        for (int column = 0; column < dt.Columns.Count - 3; column++)
                        {
                            PdfPCell = new PdfPCell(new Phrase(new Chunk(dt.Rows[rows][column].ToString(), font8)));
                            PdfPCell.Padding = 3;
                            PdfTable.AddCell(PdfPCell);
                        }
                    }
                    PdfTable.SpacingBefore = 15f; // Give some space after the text or it may overlap the table            
                    pdfDoc.Add(PdfTable); // add pdf table to the document   
                }
                pdfDoc.Close();
                Response.ContentType = "application/pdf";
                Response.AddHeader("content-disposition", "attachment; filename= " + heading + ".pdf");
                System.Web.HttpContext.Current.Response.Write(pdfDoc);
                Response.Flush();
                Response.End();

Estate_Hub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proptiwise.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Estate_Hub/Views/Front/ApplicationRejectedByLandlord.cshtml
@{
    ViewBag.Title = "ApplicationRejectedByLandlord";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
        <div class="modal-body">
          
            @using (Html.BeginForm("ApplicationRejectedByLandlord", "Front", FormMethod.Post, new { @id = "ApplicationRejectedByLandlord", @name = "ApplicationRejectedByLandlord", @enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">

               
                    @Html.ValidationSummary(true)
                    <div class="form-group no_mrg clearfix">
                        <span class="col-md-12">
                            @Html.Label("Reason To Reject Application" , new { @class = "control-label" })
                            <textarea name="Comments" class="form-control" rows="3" />
                          
                        </span>
                    
                    </div>
                    <div class="form-group no_mrg clearfix text-center">
                        <input type="submit" value="Reject" class="btn btn-primary" />

                    </div>
                </div>

            }

        </div>
   

Estate_Hub/Views/Front/ConvertToPdf.cshtml
@model Proptiwise.Models.tbl_inventory

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="witdh=device-witdh" />
    <title>inventory</title>
</head>
<body>
    <div>
        <h4>Inventory Details</h4>
    	<hr />
        <table class="table">
            <tr>
                <td>
                    <label>Name</label>
                </td>

                <td>
                    @Model.Name
                </td>
            </tr>
            <tr>
                <td>
                    <label>Address</label>
                </td>

                <td>
                    @Model.Address
                </td>
            </tr>
            <tr>
                <td>
                    <label>Quantity</label>
                </td>

                <td>
                    @Model.Quantity
                </td>
            </tr>
            <tr>
                <td>
                    <label>Modal</label>
                </td>

                <td>
                    @Model.Modal
                </td>
            </tr>
            <tr>
                <td>
                    <label>Serial</label>
                </td>

                <td>
                    @Model.Serial
                </td>
            </tr>
            <tr>
                <td>
                    <label>Cost</label>
                </td>

                <td>
                    @Model.Cost
                </td>
            </tr>
            <tr>
                <td>
                    <label>Comment</label>
                </td>

                <td>
                    @Model.Comment
                </td>
            </tr>
            <tr>
                <td>
                    <label>Brand</label>
                </td>

                <td>
                    @Model.Brand
                </td>
            </tr>
            <tr>
                <td>
                    <label>Building Name</label>
                </td>

                <td>
                    @Model.Building.BuildingName
                </td>
            </tr>
            <tr>
                <td>
                    <label>Inventory Type Name</label>
                </td>

                <td>
                    @Model.inventory_type.InventoryTypeName
                </td>
            </tr>
            <tr>
                <td>
                    <label>Property Name</label>
                </td>

                <td>
                    @Model.Property.PropertyName
                </td>
            </tr>
            <tr>
                <td>
                    <label>Area Name</label>
                </td>

                <td>
                    @Model.tbl_area.AreaName
                </td>
            </tr>
        </table>
    </div>

</body>
</html>

Estate_Hub/Views/Front/ForgetPassword.cshtml
@using Proptiwise.Models;
@{
    ViewBag.Title = "ForgetPassword";
    Layout = "~/Views/Shared/BannerMaster.cshtml";
}

<section class="login_panel">
    <div class="login_wrapper clearfix">
        <form class="form-signin" role="form" method="post">
            <h2 class="form-signin-heading" style="color:black;">Forget Password</h2>
            <span>
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <input type="email" class="form-control" name="Email" pattern="^\w+([-+.']\w+)*&#64;\w+([-.]\w+)*\.\w+([-.]\w+)*$" oninvalid="setCustomValidity('Enter Valid Email')" oninput="setCustomValidity('')" placeholder="Email address" required autofocus>
            </span>

            <br />
            <span class="btn_area"><button class="submit_btn" type="submit">Get Password</button></span>

        </form>

    </div>

</section>
@if (ViewBag.Message != null)
{

    <div id="myModal" class="modal hide fade modalErrorMsg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">

        <div class="modal-body" style="">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <p>@ViewBag.Message</p>
        </div>

    </div>

}

Estate_Hub/Views/Front/GenerateDocuments.cshtml
@{
    Layout = null;
}
<div class="modal-dialog">
    <div class="modal-content">
        <div id='myModalContent'>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 style="color:black;">GenerateDocuments</h4>
            </div>
            <div class="modal-body">
                <section class="clearfix">
                    <div class="col-md-12">
                        @using (Html.BeginForm("GenerateDocuments", "Front", FormMethod.Post))
                        {
                          <div class="form-group clearfix">
                            <h4>Select Tenants</h4>
                            <p>Choose which tenants should be added to this document. A separate document will be generated using the data stored for each tenant you specify here. <strong>Only tenants with leases are shown.</strong></p>
                        </div>
                        <div class="form-group clearfix">
                            <h5>Tenants</h5>
                            <span class="col-md-12">
                                @Html.DropDownList("TenantId", ViewBag.TenantList as SelectList)
                            </span>
                        </div>
                        <div class="form-group clearfix text-center">
                            <button class="btn btn-primary" type="submit">Download</button>
                        </div>
                        }
                    </div>

                </section>
            </div>
</div>
</div>
</div>

Estate_Hub/Views/Front/detailarticle.cshtml
@model Proptiwise.Models.Blog
@using Proptiwise.Models
@{
    ViewBag.Title = "detailarticle";
}

<h2>detailarticle</h2>
<p>@Model.Content_detail1</p>

Estate_Hub/Views/Front/tenant_otherInfotedit.cshtml
@model Proptiwise.Models.Tenant
@using Proptiwise.Models
@{
    ViewBag.Title = "tenant_commentedit";
    Layout = null;
}




<link href="~/Content/Site.css" rel="stylesheet">


<style>
    .modal-body dl dd {
        margin: 0 !important;
    }
</style>


<script type="text/javascript">
    function Fill() {
        document.getElementById("RemHidden").value = "";
    }
</script>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="model_title">Other Information</h4>
</div>
            @using (Html.BeginForm("tenant_otherInfotedit", "Front", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Tenant_Id)
                <div class="modal-body">
                

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)

                        <div class="form-group clearfix">
                            <div class="col-md-6 col-sm-6">
                                @Html.LabelFor(model => model.MaritalStatus, new { @class = "control-label" })
                                @Html.DropDownList("MaritalStatus", new List<SelectListItem>
                                {
                                    new SelectListItem{ Text="Single", Value = "1" },
                                    new SelectListItem{ Text="Married", Value = "2" },
                                    new SelectListItem{ Text="Separated", Value = "3" },
                                    new SelectListItem{ Text="Divorced", Value = "4" },
                                    new SelectListItem{ Text="Widowed", Value = "5" },
                                    new SelectListItem{ Text="Domestic Partnership", Value = "6" }
                                 }, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MaritalStatus)
                            </div>
                            <div class="col-md-6 col-sm-6">
                                @Html.LabelFor(model => model.IfVisa, new { @class = "control-label" })
                                @Html.DropDownList("IfVisa", new List<SelectListItem>
                                {
                                    new SelectListItem{ Text="Yes", Value = "1" },
                                    new SelectListItem{ Text="No", Value = "2" }

                                 }, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IfVisa)
                            </div>

                        </div>
                        <div class="form-group clearfix">
                            <div class="col-md-6 col-sm-6">
                                @Html.LabelFor(model => model.Pets, new { @class = "control-label" })
                                @Html.DropDownList("Pets", new List<SelectListItem>
                                {
                                    new SelectListItem{ Text="Yes", Value = "1" },
                                    new SelectListItem{ Text="No", Value = "2" }
                                 }, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Pets)
                            </div>
                            <div class="col-md-6 col-sm-6">
                                @Html.LabelFor(model => model.ifPets, new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.ifPets, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ifPets)
                            </div>

                        </div>
                        <div class="form-group clearfix">
                            <div class="col-md-6 col-sm-6">
                                @Html.LabelFor(model => model.Children, new { @class = "control-label" })
                                @Html.DropDownList("Children", new List<SelectListItem>
                                {
                                    new SelectListItem{ Text="Yes", Value = "1" },
                                    new SelectListItem{ Text="No", Value = "2" }
                                 }, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Children)
                            </div>
                            <div class="col-md-6 col-sm-6">
                                @Html.LabelFor(model => model.IfChildren, new { @class = "control-label" })
                                @Html.DropDownList("IfChildren", new List<SelectListItem>
                                {
                                    new SelectListItem{ Text="Select", Value = "0" },
                                    new SelectListItem{ Text="1", Value = "1" },
                                    new SelectListItem{ Text="2", Value = "2" },
                                      new SelectListItem{ Text="3", Value = "3" },
                                    new SelectListItem{ Text="4", Value = "4" },
                                      new SelectListItem{ Text="5", Value = "5" },
                                    new SelectListItem{ Text="6", Value = "6" },
                                      new SelectListItem{ Text="7", Value = "7" },
                                    new SelectListItem{ Text="8", Value = "8" },
                                      new SelectListItem{ Text="9", Value = "9" },
                                    new SelectListItem{ Text="10", Value = "10" }
                                 }, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IfChildren)
                            </div>

                        </div>


                        <div class="footer_btn"><input type="submit" value="Submit" class="btn btn-info btn-block"></div>
                      
                    </div>
                </div>
            }

   